Doist/TodoistPojos

src/main/java/com/todoist/model/BaseNote.java

This small PR adds `projectId` field for Note class.

Add projectId field for Note

---

src/main/java/com/todoist/model/Sanitizers.java

Adding parenthesis to the label sanitizer

Update label sanitizer regex to add parenthesis

---

src/main/java/com/todoist/model/BaseItem.java
src/main/java/com/todoist/model/BaseProject.java

Adding "has_more_notes" boolean field to Item and Project model to map newly introduced API field.

Add "has_more_notes" field to Item and Project model

---

src/main/java/com/todoist/pojo/Collaborator.java
src/main/java/com/todoist/pojo/Item.java
src/main/java/com/todoist/pojo/Note.java
src/main/java/com/todoist/pojo/Utils.java

Also chains Collaborator constructors to unify them with Item and Note constructors.

Make collections in models unmodifiable

---

src/main/java/com/todoist/pojo/LiveNotification.java

Add is_unread field to LiveNotification

---

src/main/java/com/todoist/pojo/Filter.java
src/main/java/com/todoist/pojo/Label.java
src/main/java/com/todoist/pojo/Project.java

This PR adds `isFavorite` property to Project/Label/Filter.

Add favorite property to models

---

src/main/java/com/todoist/pojo/Tooltips.java
src/main/java/com/todoist/pojo/User.java

This PR add a couple of new properties required by empty view update.
API changes [discussion](https://twistapp.com/a/1585/ch/104900/t/371291).

Empty view update

---

src/main/java/com/todoist/pojo/Project.java

Update the limits for the project numbers (max number of projects and collaborators per project).

Increase project limits

---

src/main/java/com/todoist/pojo/UserSettings.java

SMS reminders are deprecated and will be removed soon.

Remove reminderSms from UserSettings

---

src/main/java/com/todoist/pojo/Item.java
src/main/java/com/todoist/pojo/Project.java

This PR replaces `itemOrder` and `indent` with `childOrder` and `parentId` in Item and Project models. It also adds `dateCompleted` property to Item model.

Real hierarchies

---

src/main/java/com/todoist/pojo/User.kt

This PR adds `hasPassword` field to User.

Add hasPassword field to User

---

src/main/java/com/todoist/pojo/Project.kt

This PR adds a project view style field.

Project view style

---

src/main/java/com/todoist/pojo/Item.kt

Closes https://github.com/Doist/TodoistPojos/issues/39.

Add Item.addedByUid

---

src/main/java/com/todoist/pojo/Filter.kt
src/main/java/com/todoist/pojo/Sanitizers.kt

Latest commit: https://github.com/Doist/doist-documentation/commit/bba1d5f0392d49b7b744708251c12a812d9cd3fb
For reference, here's the handbook link: https://handbook.doist.com/Product/Todoist/Name-sanitizers.md

Update model name sanitizers according to the latest spec

---

src/main/java/com/todoist/pojo/User.kt

Add weekendStartDay to User model

---

src/main/java/com/todoist/pojo/Features.kt
src/main/java/com/todoist/pojo/Filter.kt
src/main/java/com/todoist/pojo/Label.kt
src/main/java/com/todoist/pojo/Project.kt
src/main/java/com/todoist/pojo/Reminder.kt
src/main/java/com/todoist/pojo/UserPlan.kt

This PR adds model UserPlan. This model is supposed to replace hardcoded limits in related models and Restriction in Features.

Add UserPlan

---

src/main/java/com/todoist/pojo/ViewOption.kt

This PR just adds `TODAY` as a supported view type for view options.

Add TODAY as a valid ViewOption type

---

src/main/java/com/todoist/pojo/Sanitizers.kt

Spec update PR: https://github.com/Doist/doist-documentation/pull/758

Update name sanitizers 

---

src/main/java/com/todoist/pojo/Item.kt

This PR adds description to item.

Add description

---

src/main/java/com/todoist/pojo/Item.kt

This PR adds constants for text limits in Item.

Add limits to Item

---

src/main/java/com/todoist/pojo/Item.kt

Ref: https://twist.com/a/1585/ch/421147/t/2207318/c/66541928

Update item content length limit to 500

---

src/main/java/com/todoist/pojo/Collaborator.kt
src/main/java/com/todoist/pojo/Item.kt
src/main/java/com/todoist/pojo/Note.kt
src/main/java/com/todoist/pojo/Project.kt
src/main/java/com/todoist/pojo/Reminder.kt
src/main/java/com/todoist/pojo/Sanitizers.kt
src/main/java/com/todoist/pojo/Section.kt
src/main/java/com/todoist/pojo/Workspace.kt
src/main/java/com/todoist/pojo/WorkspaceMember.kt

This PR adds the new models to support teams as well as updates existing models with new properties.

Teams MVP - New models and attributes for existing models

---

src/main/java/com/todoist/pojo/WorkspaceMember.kt

Ref: https://github.com/Doist/Todoist-Android/pull/2556

Add workspaceId to member model

---

build.gradle

This PR updates kotlin version.

Kotlin version update

---

src/main/java/com/todoist/pojo/ViewOption.kt

This PR simply adds 2 new types of grouping and sorting.

Add group and sort workspace option

---

build.gradle

Ref: https://github.com/Doist/Todoist-Android/pull/3063

Bump Kotlin to 1.6.21

---

src/test/java/com/todoist/pojo/CollaboratorTest.kt

Add some tests for Collaborator project state changes

Add collaborator project state test

---

src/main/java/com/todoist/pojo/HabitPushNotifications.kt
src/main/java/com/todoist/pojo/NotificationFeature.kt
src/main/java/com/todoist/pojo/UserSettings.kt

This is part of the TD Push Notifications DO.
API Spec: https://docs.google.com/document/d/1TX5Q43OTjS1XFjFgvXxmlQ7-e1HvCNfi7wFcBfGUVt8/edit

Add API models for push notification settings

---

src/main/java/com/todoist/pojo/UserSettings.kt

Adds a new `resetRecurringSubtasks` property to `UserSettings`.

Add parameter to UserSettings

---

src/main/java/com/todoist/pojo/Features.kt

Teams flag
